### ISSUE TITLE
FAQ - Remove outdated information from FAQ and review existing entries 🔧 

### ISSUE THREAD

**Issue by heinezen** [corona-warn-app/cwa-website#971]
## Motivation

Due to the now substantial version history of the CWA, the FAQ contains a lot of legacy information. Content describing issues/fixes for several releases is often mixed together, creating possibilities for confusion. Formatting also varies between the individual entries.

## Suggested change

Overhaul all entries by removing, improving or reordering them

- [x] Check existing entries for relevance
- [x] Check existing entries for outdated info
- [ ] Trim entries that are overly long or split them into separate issues
- [ ] Use consistent wording (for terminology: https://github.com/corona-warn-app/cwa-website/issues/524) and formatting, e.g. instructions should always be a enumerated list and the app name should be "Corona-Warn-App" with hyphens
- [ ] Move obsolete/resolved entries to *somewhere else* (either through https://github.com/corona-warn-app/cwa-website/pull/894 or other means)
 
----

FAQ entries that were updated:

- [x] who_can_help (https://github.com/corona-warn-app/cwa-website/pull/1083)
- [x] international_phone_numbers (https://github.com/corona-warn-app/cwa-website/pull/1078)
- [ ] further_details
- [ ] update_iOS
- [ ] cause2001  (https://github.com/corona-warn-app/cwa-website/pull/1081)
- [x] access-list  (https://github.com/corona-warn-app/cwa-website/pull/1069)
- [ ] battery_optimization_background  (https://github.com/corona-warn-app/cwa-website/pull/1085)
- [ ] no_risk_update_ios14 (https://github.com/corona-warn-app/cwa-website/pull/1075)
- [x] ios_black_screen  (https://github.com/corona-warn-app/cwa-website/pull/1077)
- [ ] encounter_but_green
- [ ] android_location
- [ ] qr_scan
- [x] qr_test  (https://github.com/corona-warn-app/cwa-website/pull/1073)
- [ ] red_card_how_to_test
- [x] battery (https://github.com/corona-warn-app/cwa-website/pull/1084)
- [ ] no_risk_update_ios
- [x] ios_power_save (https://github.com/corona-warn-app/cwa-website/pull/1076)
- [ ] no_risk_update
- [x] huawei_honor (https://github.com/corona-warn-app/cwa-website/pull/1079)
- [x] ENError13 (https://github.com/corona-warn-app/cwa-website/pull/1080)
- [ ] exposure_check
- [ ] cause9002_recovery
- [x] various_device_problems (https://github.com/corona-warn-app/cwa-website/pull/1071)
- [ ] minimum_requirements
- [ ] ios135
- [ ] beta_ios
- [ ] rooted_devices (https://github.com/corona-warn-app/cwa-website/pull/1072)
- [ ] available_languages
- [ ] interoperability_countries
- [ ] age_restriction
- [ ] apk (https://github.com/corona-warn-app/cwa-website/pull/1070)
- [ ] other_platforms (https://github.com/corona-warn-app/cwa-website/pull/1074)
- [x] where_to_get (https://github.com/corona-warn-app/cwa-website/pull/1082)
- [ ] QRcodes
- [ ] keys_matches
- [x] close_app (https://github.com/corona-warn-app/cwa-website/pull/1051)
- [ ] days_last_risk_encounter
- [x] bluetooth_off (https://github.com/corona-warn-app/cwa-website/pull/1052)
- [ ] ios_logging_bt
- [x] backup (https://github.com/corona-warn-app/cwa-website/pull/1042)
- [x] new_device (https://github.com/corona-warn-app/cwa-website/pull/1047)
- [ ] delete_random_ids
- [x] risk_info (https://github.com/corona-warn-app/cwa-website/pull/1044)
- [ ] test_multiple_devices
- [ ] test_in_other_country
- [x] sick_leave (https://github.com/corona-warn-app/cwa-website/pull/1045)
- [ ] recovered
- [ ] hearing_impaired
- [x] risk_update_24 (https://github.com/corona-warn-app/cwa-website/pull/1043)
- [x] mobile_data_costs (https://github.com/corona-warn-app/cwa-website/pull/1049)
- [ ] ENF_version
- [ ] dissimilar_indication_of_risk_status
- [x] mutation (https://github.com/corona-warn-app/cwa-website/pull/1048)
- [x] encounter_count_19 (https://github.com/corona-warn-app/cwa-website/pull/1221)
- [x] encounter_19_calc (https://github.com/corona-warn-app/cwa-website/pull/1050)
- [ ] encounter_criteria
- [ ] low_risk_green
- [ ] encounter_same_person
- [ ] count_per_day
- [ ] have_to_use
- [x] numbers_RKI (https://github.com/corona-warn-app/cwa-website/pull/1046)
- [ ] central_entity
- [ ] contact_diary
- [ ] why_oss
- [ ] oss_complete
- [ ] dev_status
- [ ] how_to_contribute

**Comment by MikeMcC399** [comment]
@heinezen 

Has there been any announcement about the minimum version of CWA which is still supported? 

Perhaps the main FAQ could cover the current release and the previous release, moving older information to the "somewhere else" place? I expect that most devices will auto-update to the latest version when it is released.

**Comment by Ein-Tim** [comment]
Forwarding what @dsarkar shared with us [here](https://github.com/corona-warn-app/cwa-website/pull/895#issuecomment-807009232):

> [...] On the server the min. req. version iOS 1.5.3 and Android 1.0.4 (!). There shouldn't be users with working CWA versions older than those mentioned, and all FAQ entries referring to < iOS 1.5.3 / Android 1.0.4 can be archived.

> This is relevant for archiving older FAQ articles.
In this case here, it means, we still need the info of the old article.

**Comment by MikeMcC399** [comment]
If the decision for Android is to continue to keep FAQ articles going back to CWA Android 1.0.4 then this is no relief for simplifying the FAQs. As far as I could see on a quick run through the articles there is nothing which can be removed for Android.

**Comment by Ein-Tim** [comment]
After a quick look at the FAQ I found this entries that can be removed (iOS):

- https://www.coronawarn.app/de/faq/#app_does_not_open
- https://www.coronawarn.app/de/faq/#migration_Apple

We should also consider to remove articles which talk about iOS 13.5 - 1.6.1 (like https://www.coronawarn.app/de/faq/#ENError5 and below this entry).

**Comment by heinezen** [comment]
@MikeMcC399 @Ein-Tim 

Thanks. I'll start going through everything today, categorize the entries and look for errors. The results will be posted here for feedback.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
# Part 1

### Genereal issues/remarks

- Corona-Warn-App spelled differently across English/German
- Phone number format should be international (+49 ...) --- but not 0800 numbers !
- **Important**: FAQ entries should actually answer a question and not something completely differently
    - Remove TMI stuff 
    
- Use a unified format for instructions
    - enumerated list
    - UI element names enclosed in ''
    - Traversing menu items should be indicated by an arrow: ->
    
- For entries with UPDATE:
    - need clarify which info is outdated and which is still relevant

### who_can_help

- Split into multiple entries
    - Merge Hotline national/international entries (international_phone_numbers)
    - New entry for "where to find the responsible health authority"


- "If the test result is not available in the Corona-Warn-App..." section
    - very general, what question does it answer?

- Link to possible outdated blog entry from August: https://www.coronawarn.app/de/blog/2020-08-25-notes-qr-codes/
    - better link to FAQ entry qr_scan
    
- Link to Bundesregierung page is about CWA, but link to RKI is about Corona in general
    - New entry for general Corona (not CWA!) updates from Breg/RKI?

English issues:
> You can reach the technical hotline from Monday to Saturday from 7 a.m. to 10 p.m. (except on **German public holidays**), and it is free of charge for you within Germany.

- Should be **national** holidays (bundesweit) so that this is not confused with federal holidays


> The various feedback channels of the [Corona-Warn-App-Community](https://www.coronawarn.app/de/community/) will help you with your questions about the open source project of the Corona-Warn-App.

- embedded link links to german page


### international_phone_numbers

- Should be merged with national phone numbers, so that we can link to it from other places in the FAQ
    - many older entries only reference the national phone number

### "News" section

- These are not questions, why? 
- Would be better as blog entries?

### further_details

- Entry: "In-App Statistiken ab Release 1.11" is WIP, it will explain in more detail the four statistic cards. 
- Key "further_details" is not descriptive
    - better use "in_app_stats"
    - anchor can't be changed, since this FAQ entry is linked from within the app!

> The number of new infections is published once a day by the Robert Koch Institute (RKI). 'Yesterday' means that the value considers all reported new infections from the previous day until 23:59. 

- Clarify that 'Yesterday' refers to something in the UI (the R-value card)
    - or remove it because it is only relevant for the R-value card

----
    
- Link the first mention of nowcasting to: http://www.rki.de/covid-19-nowcasting


English issues:
- Last sentence starts with "However", but german entry does not


### update_iOS

> More information can be found in [this](https://www.coronawarn.app/en/faq/#ios135) FAQ entry.

- More information about what? Clarify!
    - "More information on how to upgrade to iOS 13.7"

- Clarify that CWA switch to ENFv2 in CWA version ??? and therefore requires it
    
- ios135 answers the same question, although with a slightly different approach
    - Merge entries?

### cause2001

- List with instructions needs formatting update (see above)

### access-list

- Key "access-list" is not snake case

- "Some firewalls" -> "some firewall settings" (english/german)

- "contacting the backend" -> "contacting its test result/verification backend" (english/german)

- format access list as HTML list

### battery_optimization_background

> When you switch on the prioritized background activity on **some Android devices**, the battery optimization for the Corona-Warn-App is not turned off on OS level. This is a known limitation for **a limited number of Android devices**.

- Which ones?
- Rephrase to "is not turned off [...] immediately"

English issues:
- "switch on" -> "enable"

### no_risk_update_ios14

- Still relevant?
- List with instructions needs formatting update (see above)

> However, it will take 24 hours until the app resumes the data collected so.

- Grammar?
- Is it still 24 hours? might be 4 hours because of the 6x per day update
    - On mobile data there is only one update per 24 h

German issues:
- "1x" -> "einmal"

### ios_black_screen

- Still relevant? Yes, in the AppStore relevant 
- List with instructions needs formatting update (see above)

### encounter_but_green

- entry explains a lot which is already explained elsewhere
    - encounter_19_calc
    - encounter_criteria

- second paragraph is very confusing due to nested sentences
- needs mention of encounters which are filtered out by the app

- cwa-risk-assessment.md is still outdated!

----

> Jedem dB-Wert lässt sich eine Entfernung im Freiraum (d.h. ohne Hindernisse im Signalweg) zuordnen.

- No mention of this in english entry
- Not accurate enough
    - we use dB ranges in the CWA

----
German issues:
> Als Nächstes wird für jede Positivkennung anhand aller dazu passenden Zufalls-IDs **geschätzt**, wie lange die Begegnungen jenes Tags insgesamt gedauert haben und wie nahe die Smartphones sich dabei im Durchschnitt waren.

- analysiert (like in the english entry)

### android_location

- List with instructions needs formatting update (see above)

> This notification is not applicable for Android 11 phones and will be removed in one of the following updates of the Corona-Warn-App.

- Implemented? Yes, the text has changed.

> Here you can allow or deny other apps to use your location, but since Corona-Warn-App doesn't need this permission, it doesn't even appear in the list.
> Again, as described above: You should not deactivate 'Use location' under 'Settings' > 'Security & Location' > 'Location', because this is a prerequisite for exchanging the encrypted random IDs.

- Explanation issue: We should explicitly say what the difference between the BLE location and GPS location is
    - BLE = localized location tracking
    - GPS = globalized location tracking (not used in CWA)

German issues:
> Sehen Sie sich die Liste der Apps an, die auf Ihren Standort zugreifen können, wenn Sie es zulassen. Sie sehen: Die Corona-Warn-App ist nicht aufgeführt.

- "Sie sehen" is not in the english version of the entry

### qr_scan

- Section "The code was already used once for registration" could mention test_multiple_devices


### qr_test

- Link to FAQ entry with TAN Hotlines instead of mentioning phone numbers directly

English issues:
- Missing single quote: 'Display Test' -> 'Delete test

### red_card_how_to_test

- The linked PDF is not great if you are on mobile. There should be a mobile version or image.

English issues:
- "screened" -> "tested"


### battery

- List with instructions needs formatting update (see above)

> The Corona-Warn-App uses the **latest** Bluetooth technology: **Thanks to the** Exposure Notification API from Apple and Google, the app can use the energy-efficient BLE (Bluetooth Low Energy) technology.

> Die Corona-Warn-App nutzt die **vorhandene** Bluetooth-Technologie der Endgeräte. **Da die App die** Exposure Notification API von Apple und Google verwendet, unterstützt sie die energieeffiziente Bluetooth-Technologie BLE (Bluetooth Low Energy).

- English version is "biased" and should use a more neutral tone

> This means that a frequently and intensively used phone has a very low percentage of battery consumption per app. On the contrary, if you use your phone mainly to make phone calls and only occasionally stream music or use social media, the percentage per app will be relatively high.

- Wording? Is it understandable?

----

- "Note for Android phones" -> "Note for Android devices"

----

> Here you can deny other apps permission to use your location **if you don't think** they need it.

> Hier können Sie den installierten Apps die Berechtigung für den Standortzugriff entziehen, wenn diese nicht benötigt wird.

- Difference in wording

### no_risk_update_ios

- List with instructions needs formatting update (see above)

- Why is there a blogpost on LinkedIn?
    - and it's german only???

----
> Make sure that exposure logging is active.

- How?

### ios_power_save

- iOS 13.6.1 is not supported anymore, so this entry should be moved to "Resolved"

### no_risk_update

- This entry is loooooooooooooong (split or trim content?)

> Make sure that exposure logging is active.

- How?

----

- "de-activate" -> "deactivate" (english german)


English issues:

> You do so directly in the energy saving settings. of your phone.

- Remove dot

### max_power_save

### huawei_honor

- Move to resolved section

- What is EMUI 4: The custom OS

> According to current information, a system update seems to be available for newer Huawei devices that is explicitly intended to fix the problems with Corona-Warn-App.

- Link to official info
- Tell users to install it

> The GitHub community has compiled suggestions for making additional settings and has also linked information about the system update. You can find all the details in this GitHub issue.

- Issue is closed


### ENError13

- Still relevant? Yes. Occurs typically after CWA updates. Notification might be suppressed in future.
- Do not have so many paragraphs with single sentences

### exposure_check

> The log has a fixed limit of 100 entries on iOS devices. On Android devices the limit is 300 entries. If there are more entries, only the latest are kept.

- Is this still true?

German issues:
- "drei-Punkte-Icon" -> "Dreipunktmenü"

### cause9002_recovery

- Still relevant?

- German heading starts with "[Google/Android]: ", but the english one does not 

> Resetting the data also means that the information on how long your app has been active is lost (the number of active days is set to 0). 

- This display was removed in current CWA

----
 
- The technical background section suffers from too much information

### various_device_problems

- List with instructions needs formatting update (see above)

> Since I installed the app, my phone sometimes behaves oddly. Example: There are occasional problems with other apps and devices that use Bluetooth. What can I do?

- Question is in text instead of heading

----

- Still relevant?
    - What is the current status?
    - Examples for devices?

### minimum_requirements

- Android: Link to googleplay entry (aka "Why are Android 6 and Google Play Services minimum requirements?")
    - Already done for Apple section

- "v2 version" -> "ENFv2 version"
    - there is a confusion: Currently it is ENF version 1.8, but API 2, not API 1. In the Android devices ENF version number is shown as 18nnnnnnnnn

> See also [[Apple/iOS]: Why is iOS 13.7 a minimum requirement?](https://www.coronawarn.app/en/faq/#ios135) and the blog articles [Telekom and SAP to make Corona Warn app available for iOS 12.5.] and [Corona-Warn-App version 1.12 comes with two new features]

- Links to blog articles could be removed since they can also be found in the linked FAQ entry
- Remove the dot after 12.5 (english)

**Comment by heinezen** [comment]
@Ein-Tim @MikeMcC399 above are our remarks and notes so far. You can already give feedback :)

There will be a part 2 for the other entries (probably on Thursday)

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Thanks @heinezen, looks good so far, some thoughts & remarks:

### who_can_help

Don't forget that this FAQ is linked to from everywhere on the www.coronawarn.app page ("Wer hilft bei Corona-Warn-App Fragen?").

### further_details

Use the redirect to change the anchor?

### update_iOS

Was created to link from in-app update screen. See https://github.com/corona-warn-app/cwa-app-ios/issues/2045. If it's not getting implemented then merge with ios135.

### no_risk_update_ios14

Not relevant anymore IMHO, should be moved to solved section.

### encounter_but_green

This entry is linked to from the app if the user had low risk encounters. It should probably be adapted to only explain why the encounter is green and how the user should behave. Details about the risk calculation should be moved to encounter_19_calc and encounter_criteria. 

### no_risk_update_ios

Blogpost was published when press wrote about non working background updates on iOS. Why it's on Linkedin, idk. 😁

### no_risk_update

Entry is only about android but isn't "no_risk_update_android", maybe change anchor (-> redirect).

**Comment by heinezen** [comment]
# Part 2
### ios135

- Key "ios135" does not fit anymore
- entry explains more about 13.7 than 12.5
    - more details about versioning for non-techical users?

> The version 1.12.1 is already available.

- Must refer to $current_version
- Vertical bar in english version after bullet points, but not in german version

> More details about the system requirements can be found in this FAQ entry.

- Links to minimum requirements, which contains **less** information

- Last two sentences: Repetition of leider/unfortunately

### beta_ios

- Unclear what support means (ability to install the app? no support for bug fixing? i assume it is only the latter)

### rooted_devices

- Answer does not match the question
    - It can be used on a rooted device
    - Rooted devices will just not receive official support

English issues:
    - "Also" in the heading should be removed

### googleplay

-

### available_languages

- Link to hotline FAQ entry

> Please note that many countries release their own Corona tracking apps. Because the German Corona-Warn-App is also available in the app stores and play stores of these countries, the Corona tracking apps could be mixed up. Therefore, make sure that you download the app for your country.

- Does not really fit to an entry about languages
    - Better suited for entry: international
- Entry touches several different topics
- New FAQ entry?
    - I have to travel abroad. Can I still use the Corona-Warn-App?

>  Therefore, make sure that you download the app for your country.

- Should be: For the country you are currently residing in
    - but CWA can also accept tests from other countries via TeleTAN (SEE test_in_other_country)


### interoperability_countries

- Can tests in the respective countries still only be submitted through the country's own app?

- Does the phone number formatting follow any pattern?
- Germany: Email is CoronaWarnApp@rki.de, but maybe it should be the opensource@sap address?
- spellchecks and checks for missing information might be necessary
- Slovenia errors:

> Ministry of Public Administration (MJU) and **Ministry of Public Administration (MJU)**

-> Ministry of Public Administration (MJU) and National Institute of Public Health (HIJZ)
    - german entry: use "und" instead of "and"
- what does DPO stand for?
- HIJZ phone number missing

### age_restriction

- Reason for the age of 16 are likely privacy regulations
- Link to CWA Privacy notice

### apk

- Outdated
    - there is an Fdroid fork now
    - It is not made by the RKI -> no support
    - made by the community using the code from CWA
    - Link to it?

> Furthermore, the app only works with Google Play Services.

- google play services are not required anymore

- Links need to be updated with newer issue links:
    - https://github.com/corona-warn-app/cwa-app-android/issues/1483

> Furthermore, there is an initiative in the developer community to make the Corona-Warn-App executable independently of Google Play Services via appropriate extensions. Details can be found in the issue corona-warn-app/cwa-app-android#75.

- If this refers to microG, then the initiative has been successful


### other_platforms

- Link/mention CCTG?


### where_to_get

- Links to store page?

### QRcodes

> At the moment, many families are tested at the airport after returning from their holidays.

- "at the moment" might refer to last year
- mentioning airports specifically is weird

> For each family member that is being tested, they get a leaflet that displays a QR-Code.

- Link to an example

----

- A lot of the information is already mentioned in qr_scan
    - 1. - 4. are just qr_scan
    - 5. is the only time multiple QR codes are mentioned

----

- Restructure entry with more direct info
    - (Apparently) multiple people are sometimes tested at once
    - If that's the case: Everyone should scan their respective QR code in their own device
    - QR codes of kids/others who do not have their own device should not be scanned
    - For scanning the QR code, refer to qr_scan

### keys_matches

> What **do** the exposure check logs **show**?

> Was **bedeutet** die Überprüfung auf mögliche Begegnungen?

- Minor discrepancy in heading

----

> Exposure checks
> This value does not reflect the number of encounters. Please tap one level further: This is where the checks of up to 15 days are logged (today plus the last 14 days). Selecting an entry leads to a detailed view with the corresponding time stamps and the number of matched keys.

- Shouldn't explain what it's not first -> Rearrange explanation

> Provided Key Count (Apple) | Number of keys (Android)

> Matched Key Count (Apple) | Number of matches (Android)

- iOS instead of Apple

> If your risk status stays green, that is, 'Low Risk', find more information at [An encounter has been reported, but the risk status stays green](https://www.coronawarn.app/en/faq/#encounter_but_green).

- Needs more explanation
    - "Your risk status can remain at "Low risk" (green card)despite having severa encounters. Find more information at ..."

> Date and time at which the check happened.

- "check" -> "exposure check by the app"

German issues:
- "Gültigkeitsdatum" -> "Validierungszeitstempel"


### close_app

> Yes. As long as you have activated exposure logging in the app and Bluetooth is on, encounters are logged in the background. The app itself doesn't have to be open for this.

- Additional info: Exposure logging is done on OS level as long as a COVID app is installed.

German issues:
> Sicherheitshalber öffnen Sie die App täglich nach Ablauf von 24 Stunden einmal.

- "einmal am Tag" is okay too, especially since the app updates more frequently now

### days_last_risk_encounter

- Resolved; since CWA 1.13 dates for green and red are shown

### bluetooth_off

> Therefore, make sure to have Bluetooth and for Android, the location services, active whenever you meet someone, be it guests or when you're on the road.

- Improve readability (german/english)


> You can deny other apps to use your location, if you want: see [I'm asked to activate my location](https://www.coronawarn.app/en/faq/#android_location).

> Für alle anderen Apps können Sie die Standortverwendung ausschalten, wenn Sie das möchten: siehe [Meldungen zur Aktivierung der Standortverwendung](https://www.coronawarn.app/de/faq/#android_location).

- Link text does not match entry heading *[Google/Android]: When activating exposure logging or Bluetooth I'm asked to activate my location. Do I have to do this?*

### ios_logging_bt

-

### backup

English issues:
- "back up" -> "backup" (heading)


### new_device

English issues:
- *Corona Alert app* :smile:

> [...] please note [this ](https://www.coronawarn.app/en/faq/#test_multiple_devices)FAQ entry.

- Link text includes space after "this"

### delete_random_ids

- Last paragraph has discrepancy between english and german version
    - improve formatting
    - use the same descriptions for the steps
    - description needs more details (e.g. where are the settings?)

English issues:
- "re-install" -> "reinstall"

German issues:
- "Neu-installation" -> "Neuinstallation"


### risk_info

- needs update on wording

> If you are diagnosed with COVID-19, you can upload your diagnosis keys to the server.

- "server" -> "test result server"

> If there is a match between a key downloaded from the server and a key saved locally on your device, this means you were exposed to a person who has been diagnosed with COVID-19. Matching the encounters does not require a Bluetooth connection.

- Say that the keys are compared

----

- Introduce 4.: App assesses risk based on XYZ (can link to FAQ entry)

> If there is a match between a key downloaded from the server and a key saved locally on your device, **this means you were exposed to a person** who has been diagnosed with COVID-19.

> Gibt es eine Übereinstimmung zwischen einem vom Server heruntergeladenen und einem lokal gespeicherten Schlüssel, dann bedeutet das, **dass es eine Begegnung mit einer Person gab**, die positiv auf Corona getestet wurde.

- use the english version for the german entry

German issues:
- Point out that the solution architecture document is english-only


### result_time

-

### rapid_test

-

### test_negative

-

### test_multiple_devices

- Link to hotline FAQ entry

> If you additionally want to share a positive result via your company device or any other additional smartphone, **this can be done** via a so-called TeleTAN.

> Wenn Sie darüber hinaus auch über Ihr Firmengerät ein positives Ergebnis teilen möchten, **geht dies ausschließlich** über eine sog. TeleTAN.

- difference in tone between german/english

German issues:
- "sog." -> "sogenannte"

### test_in_other_country

- Link to hotline FAQ entry

### sick_leave

German issues:
- "Teststelle" -> "Testzentrum"

### recovered

> you have the option to reactivate the app after recovering from a SARS-CoV-2

- where/how?


### hearing_impaired

- "TAN" -> "TeleTAN" (?)

### risk_update_24

German issues:
- "Zero-Rating Verpflichtungen" needs additional dash

### mobile_data_costs

German issues:
- "Datenvolumina" -> "Datenvolumen"

### ENF_version

- too much historical information

### dissimilar_indication_of_risk_status

- Key "dissimilar_indication_of_risk_status" is very long
- Actual question in text instead of heading

### mutation

- Include the titles of the linked blogposts

### encounter_count_19

- Entry talks in past tense about versions < CWA 1.9, but they are still supported on some devices
- Drop separation of "In simplified terms" and "In detail:" sections
    - both are relevant for understanding
- remove mention of 10 minutes signal attenuation time window and just keep 5 minutes

Englisch issues:
> However, in the operating system's contact log, a count is performed. However, this is not an error.

- 2x however

----

- Missing dot at end of last sentence

### encounter_19_calc

- remove mention of 10 minutes signal attenuation time window and just keep 5 minutes

> Based on the transmission risk level (III to VIII), only a factor between 0.6 and 1.6 is determined. The weighted time from the previous step is multiplied by this factor, which then results in the weighted contact time. This weighted time is now used to decide what type of encounter this time slot is:

> * Weighted contact time <15 minutes: Encounter with a low risk (green).

> * Weighted contact time >=15 minutes: Encounter with increased risk (red).

> Finally, all time windows of a day are considered (the weighted contact times) and added up. If the sum is >= 15 minutes, the overall status becomes red, otherwise it is green. Ultimately, this means that several 'green' encounters (time windows) can result in a red status in total. For those who would like to dive even deeper into the subject:

- Last paragraph should come before bullet points to emphasize that time windows are accumulated

English issues:
> Based on the transmission risk level (III to VIII), only a factor between 0.6 and 1.6 is determined.

- "only"?

### encounter_criteria

- Answers two questions at one -> split up
    - By which criteria are encounters evaluated?
    - how do the recommendations for action differ?

- wording is different between paragraphs:
    - "increased risk" vs. "high risk"

> As of version 1.9.1, the app also shows the last time (within the last 14 days) an encounter with increased risk took place. You can now see an exact date to better track your contacts or behaviour on that specific day.

- Should be moved to the second to last paragraph

### encounter_deletion

-

### low_risk_green

- There should be at least something like "try to minimize your encounters" with other people here, not "there is no particular need for action"

### encounter_same_person

- does the answer match the question?

### count_per_day

- same as encounter_same_person?

### have_to_use

- Should be more precise about
    - the whole app being voluntary
    - that the app functions are optional

- more than two functions
    - exposure logging
    - test retrival
    - sharing result
    - contact diary

German issues:
> nichts geschieht ohne Ihre Zustimmung.

- add "explizite" like in english version

### numbers_RKI

- question in heading could be more general about statistics

### objectives

-

### reasoning_decentralized

-

### cost_benefit

-

### constraints

-

### non_dev_related

-

### central_entity

- Additional info: Expousure events are stored by OS ENF, not by app

### backend_ops

-

### client_server

-

### contact_diary

- Heading is not a question
- mention that fearure requests can be found/made on Github
    - link to contact jounal overview

English issues:
- "extension by functions" -> "extension by features"

### why_oss

- Second sentence is in first paragraph in english version, but in second paragraph in germa version

> through reviews and pull requests

- very technical
    - better: "through code reviews and contributions via Pull Requests"

### oss_complete

- Link to Github!!

### dev_status

> We will be able to publish information as soon as it is available on the issue as to whether the code in GitHub is really the same as that in the app in the respective app stores ('reproducible builds'). You can find further information on the progress of this issue in the respective GitHub issue.

- Needs clarification

### how_to_contribute

> removing mistakes in the source code, helping with the documentation, raising questions or commenting on the project.

- and reporting bugs

German issues:
> Die Zusammenarbeit innerhalb der Community unterliegt einem Code of Conduct. Alle Richtlinien zur Beteiligung findest Du hier.

- informal Du

### github

-

### coc

-

**Comment by Ein-Tim** [comment]
Hey @heinezen, only two comments:

### ios135

- Shouldn't say something about the app version minimum, it's about the iOS version

### hearing_impaired

- Yes, "TeleTan" (See https://github.com/corona-warn-app/cwa-documentation/blob/master/.spelling#L99-L102)

Have nice easter days!

**Comment by heinezen** [comment]
Starting today, the FAQ entres will gradually be updated with what we found. We will make a separate PR for each entry which I will link in the list in the top post. PRs will stay open for some time to get feedback. The PR will also include a changelog in the description.

I'll start with the least complicated entries and we will gradually work ourselves through the more sophisticated changes.

Happy easter!

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
@Ein-Tim @MikeMcC399 A new batch of entries has landed!

**Comment by MikeMcC399** [comment]
@heinezen 
Thank you for the heads-up. I will take a look at the new PRs.

**Comment by Ein-Tim** [comment]
I added my suggestions & remarks. Weren't that much 👍

**Comment by MikeMcC399** [comment]
@heinezen 
I have finished reviewing and commenting. Back to you now!

**Comment by Ein-Tim** [comment]
@heinezen 

You mentioned the entry `update_ios` [here](https://github.com/corona-warn-app/cwa-website/issues/971#issuecomment-810117566), I think it could be merged with `ios135` now for the reason I also closed https://github.com/corona-warn-app/cwa-app-ios/issues/2045.

**Comment by heinezen** [comment]
@Ein-Tim @MikeMcC399 Thank you both for your feedback! It's really appreaciated. 

We are going to start with merging the entries before we create the other PRs. 2.0 will also arrive soon and might take over priority for a while.

**Comment by heinezen** [comment]
> 
> 
> @heinezen
> 
> You mentioned the entry `update_ios` [here](https://github.com/corona-warn-app/cwa-website/issues/971#issuecomment-810117566), I think it could be merged with `ios135` now for the reason I also closed [corona-warn-app/cwa-app-ios#2045](https://github.com/corona-warn-app/cwa-app-ios/issues/2045).

I've mirrored this into my notes and will propose a solution, once we'll get to that entry.

**Comment by heinezen** [comment]
Sorry for not coming back to the FAQ updates for a while. We were quite busy with the releases. I'll resume the FAQ updates this month.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I definitely I agree with you. 
Also, the open PRs from @heinezen should either be made ready to be merged now or be closed. 

I don't think @heinezen will do this himself, as he has left the Corona-Warn-App Open-Source-Team, sadly.

**Comment by MikeMcC399** [comment]
- The FAQ site has been redesigned.
- This issue has not been maintained so it is no longer a useful reference of what needs to be reviewed or changed.

I suggest to close it. It is almost one year since is has been touched.

**Comment by MikeMcC399** [comment]
This remains a stale issue.
